# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: configure-fortigate-ml2
  type: puppet
  role: [controller, primary-controller]
  requires: [post_deployment_start]
  required_for: [configure-fortigate-fwaas]


#  version: 2.0.0              # tasks v2.0.0 is supporting task-based deployment
#   cross-depends:
#     - name: deploy_start
#   cross-depended-by:
#     - name: deploy_end

  parameters:
    puppet_manifest: puppet/manifests/configure-fortigate-ml2.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: configure-fortigate-fwaas
  type: puppet
  role: [controller, primary-controller]
  requires: [configure-fortigate-ml2]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/configure-fortigate-fwaas.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: configure-fortigate-nova
  type: puppet
  role: ['compute']
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/configure-fortigate-nova.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

#- id: fuel-plugin-fortinet-post-deployment-sh
#  version: 2.0.0
#  type: shell
#  role: [fuel-plugin-fortinet_role]
#  requires: [post_deployment_start]
#  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: fuel-plugin-fortinet-pre-deployment-sh
#  version: 2.0.0
#  type: shell
#  role: [fuel-plugin-fortinet_role]
#  requires: [pre_deployment_start]
#  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

- id: primary-openstack-network-agents-l3
  type: skipped

- id: openstack-network-agents-l3
  type: skipped

- id: primary-openstack-network-agents-dhcp
  type: skipped

- id: openstack-network-agents-dhcp
  type: skipped

- id: openstack-network-agents-metadata
  type: skipped

- id: primary-openstack-network-agents-metadata
  type: skipped

- id: openstack-network-networks
  type: skipped

- id: openstack-network-routers
  type: skipped
